### ISSUE TITLE
linux headers variable name is wrong in documentation

### ISSUE THREAD

**Issue by jotadepicas** [free5lot/hid-apple-patched#17]
The variable to export for header files is LINUX_HEADER_DIR, not KERNEL_HEADER_DIR as documented in the Readme.md.

**Comment by free5lot** [comment]
Thank you! Fixed.
This documentation mistake came from PR #13.

**Comment by jotadepicas** [comment]
Sure! Btw thanks for this patch! enjoying it right now :)

**Comment by free5lot** [comment]
You're welcome :)
