### ISSUE TITLE
Remapping not working

### ISSUE THREAD

**Issue by atrauzzi** [free5lot/hid-apple-patched#2]
Just tried to run and set `swap_fn_leftctrl` to `1`.  Both control and fn stopped working.

**Comment by atrauzzi** [comment]
Just a quick update, when I set it up for a permanent install however, it works.  I'm fn-ctrl swapped!

**Comment by free5lot** [comment]
Hm, maybe something was wrong during your first attempt to run it.
Nice, it works anyway.
Please post your device information you use.

**Comment by atrauzzi** [comment]
What's the format you'd prefer for that?

**Comment by free5lot** [comment]
Something like device model, GNU/Linux version (distribution and kernel version).
And one more, do you have Eject key?

**Comment by atrauzzi** [comment]
Ubuntu 14.10
3.16.0-31-generic
MacBook Pro Late 2014 (MacBookPro11,2)

No eject key.  Power switch is in the top right of my keyboard, not a small round button.

**Comment by free5lot** [comment]
The issue was solved and everything works well for atrauzzi. I'm closing it after being solved.

And it means this patch was tested on two MacBooks Pro and works on both well.
