### ISSUE TITLE
Rebuild initframs necessary?

### ISSUE THREAD

**Issue by Bondza** [free5lot/hid-apple-patched#21]
First off, I'd like to say that is patch is awesome! :)

I needed to rebuild my initramfs to make this patched module load at boot. I don't know if this is always the case? The README does not mention anything about this, but I guessed that was what was missing after looking at the `install.sh` script. I'm guessing that this depends on if the module is part of the original initramfs image or not. Maybe it's worth adding some info about this in the README?

By the way, I'm running Fedora 23 in case that might affect this in any way.

**Comment by free5lot** [comment]
Thank you @Bondza for note and for feedback!
I added information about update-initramfs to the README.

Please try a new way using DKMS, maybe it'll be more convenient.
