### ISSUE TITLE
hid_apple swap_fn_leftctrl

### ISSUE THREAD

**Issue by iledarn** [free5lot/hid-apple-patched#27]
On 64bit ubuntu 14.04 with wireless mac keyboard some options are working, but this
options hid_apple swap_fn_leftctrl=1
is unfortunately not.
I have this type of keyboard https://www.organicdesign.co.nz/Apple_wireless_keyboard_on_Linux

**Comment by free5lot** [comment]
OK. Which options work? Are you sure you use a patched version of hid-apple kernel module?
