### ISSUE TITLE
Add permanent install script from parent repo.

### ISSUE THREAD

**Issue by atrauzzi** [free5lot/hid-apple-patched#3]
Minor item, just to make lives easier.

**Comment by free5lot** [comment]
Accepted. Will be done rather soon.

**Comment by free5lot** [comment]
And the install script is going to be a bit more complicated and enhanced, as the build-script is.

**Comment by free5lot** [comment]
Installation script was added (install.h).
It is rather clever and complicated script, please take a look. It applies patched version with options on fly and if user sees everything works fine - it makes permanent system install.

**Comment by JanmanX** [comment]
Your installation script works great, I like the "Does keyboard work as you expect? [Y/n].

Line 80-82, you try to save previous parameters, but you don't check if the module is loaded, in which case `/sys/module/hid_apple/` might not exist. Maybe place that code in your pre-check functions, where you check for existing apple module? (line 17-24)

Great job on the script!

/Jan

**Comment by free5lot** [comment]
Well, I've though of this.
On the other hand VAL=`cat NOT_EXISTING_FILE` sets $VAL to nothing and puts message to error stream (on the screen). So user will see a message about it and maybe it's a better thing, than keep it in silence?
Also it only affects on-fly test (insmod) and doesn't matter at all after system is rebooted.

**Comment by free5lot** [comment]
Oh, I have an idea, how to deal with it.
Thanks for pull request, I've merged it.

**Comment by JanmanX** [comment]
Oh, just realized now that it only affects insmod, and not long term installation.
You're right that some feedback to the user is good, but maybe we should print our own message instead?
3 warnings from cat and 2 "ERROR" messages from can make a user panic, if he/she doesn't know if it is critical for the installation (like me). :P

**Comment by free5lot** [comment]
Done, check it out.
