### ISSUE TITLE
swap_fn_leftctrl has issues with multikey shortcuts

### ISSUE THREAD

**Issue by muesli** [free5lot/hid-apple-patched#30]
Having swap_fn_leftctrl enabled, I can't use shortcuts like Ctrl-Shift-T anymore. The event grabber seems to indicate that only Ctrl+Shift is detected, the "T" isn't registered anymore.

**Comment by muesli** [comment]
Seems to be a dupe of #6. Bummer. Closing.

**Comment by free5lot** [comment]
Yes, and probably the same reason - physical limitation. Fortunately it was reported only for external keyboards, and not for Macbooks, but it won't help you sadly.
