### ISSUE TITLE
Macbook Air

### ISSUE THREAD

**Issue by rigelrozanski** [free5lot/hid-apple-patched#33]
Hey I'd love to get this operating on the macbook air, I was able to change the fn default functionality, however I'm unable to swap fn and control keys... Any tips as to where to start to mod this code to work for macbook air? -Thanks!

**Comment by smaslennikov** [comment]
How are you installing this module? What OS are you running?

**Comment by free5lot** [comment]
Hi. Are you sure you have a patched kernel module installed? The fn functionality is available in the original hid-apple too.

**Comment by free5lot** [comment]
This issue has no response and obviously should not be considered as a bug. I'm closing it, but be free to write anything here if you have some further questions.
