### ISSUE TITLE
Kernel: unknown parameter 'swap_fn_leftctrl'

### ISSUE THREAD

**Issue by damaldonadoc** [free5lot/hid-apple-patched#39]
Hi, 

On 64bit Fedora 26 - **kernel** **4.12.13-300.fc26.x86_64**, it's not working the swap_fn_leftctrl option.

Log shows: 

> kernel: hid_apple: unknown parameter 'swap_fn_leftctrl' ignored

**Comment by free5lot** [comment]
Are you sure that modified version of hid-apple is installed? Because it looks like you have the original hid-apple, not patched version.

**Comment by damaldonadoc** [comment]
I got the non-patched version installed 😞 
I tried to install the patched version, but the kernel keeps loading the old one.

I tried to remove the non-pathched module, but couldn't make it. Do you know how can I uninstall it?

**Comment by damaldonadoc** [comment]
I made it work whit [depmod override](https://github.com/free5lot/hid-apple-patched#alternative-makefile-based-installation)
```
override hid_apple * extra
```
