### ISSUE TITLE
[Ubuntu 17.10] dkms didn't work, but build/install scripts did

### ISSUE THREAD

**Issue by hawkeyetwolf** [free5lot/hid-apple-patched#45]
FYI, installation via dkms did not work for me (`modinfo hid_apple | grep parm` returned just the three standard options, not the full six of your module) on my mid-2015 MBP. I tried first from wayland, then from xorg, just for kicks, with the same result. But then I tried your build/install scripts, and boom, it works in all the places! Thank you so much for your work on this project; you get special angel points.

**Comment by free5lot** [comment]
Thank you Derek for information about  Ubuntu 17.10 and thanks for good words. I'll take a look when I have time. Glad that at least one way of module installation worked for you.

**Comment by bradlishman** [comment]
Worked for me too on 17.10 with a1502.

**Comment by free5lot** [comment]
@bradlishman worked for you via dkms or build/install script?

**Comment by bradlishman** [comment]
@free5lot via the build/install script.

**Comment by FastThenLeft** [comment]
Same here on Ubuntu 17.10 running XOrg. The dkms instructions didn't work for swapping Fn and Ctrl (it did work for the other keys). The build/install script worked for all the keys!

**Comment by anom** [comment]
@FastThenLeft  were you able to ever swap teh Fn and Ctrl key?

**Comment by free5lot** [comment]
Closing this issue as there are no complains currently about installation of patched module. Also I tested dkms way recently on Ubuntu myself and it works fine.
