### ISSUE TITLE
Module hid_apple is not currently loaded

### ISSUE THREAD

**Issue by anom** [free5lot/hid-apple-patched#52]
I'm getting the following error whilst running ./install.sh

    rmmod: ERROR: Module hid_apple is not currently loaded
    insmod: ERROR: could not insert module ./hid-apple.ko: Operation not permitted

I'm running the latest Ubuntu with the apple magic 2 keyboard through Bluetooth.

Any suggestions?

**Comment by Ndolam** [comment]
On Sun, Oct 20, 2019 at 02:25 (-0700), anom wrote:

> I'm getting the following error whilst running ./install.sh

> rmmod: ERROR: Module hid_apple is not currently loaded
> insmod: ERROR: could not insert module ./hid-apple.ko: Operation not permitted

> Any suggestions?

Try running th command as root, not an ordinary user.

**Comment by anom** [comment]
Yeah, tried running as sudo but same error.

**Comment by free5lot** [comment]
Hi @anom!
1) obvious recommendation would be run `sudo -i` before command, but may not help.
2) maybe the problem and solution are mentioned here: [linux kernel - modprobe fails with permission denied - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/543576/modprobe-fails-with-permission-denied)
3) just for your information - install.sh according to documentation is not preferable way to install this patched module/

**Comment by free5lot** [comment]
UPD. Updated link in the previous message.

**Comment by free5lot** [comment]
@anom  any update on this?
BTW just recently Bluetooth support was added (migrated from upstream) and Apple Magic 2 keyboard was reported to work properly with this patched version for both Bluetooth and USB modes. So please try again or this issue will be closed.

**Comment by free5lot** [comment]
So, we may consider it working as we have positive feedback from other users and I've tested it today once more myself.
