### ISSUE TITLE
tutorials for this kind of modifications ?

### ISSUE THREAD

**Issue by vasilakisfil** [free5lot/hid-apple-patched#58]
Hi,

I really like your work here and I would love if I could such hacks myself (for starters, specifically for Apple keyboards). I am a developer but more on the web area. But I have done C in the past. Do you have any pointers/directions/tutorials/google keywords that could help me dive into your code and apply even more custom hacks?

(Closing this issue since it's not a real issue..)

**Comment by free5lot** [comment]
You have to know 2 things - C (the language the Linux kernel is made by) and Linux kernel guidelines to make it in a proper way. I'm myself is no expert frankly :)
