### ISSUE TITLE
[Ubuntu 19.10] Tilde/grave accent key switched to < and >

### ISSUE THREAD

**Issue by TranquilMarmot** [free5lot/hid-apple-patched#60]
After installing via DKMS on a 2016 Macbook Pro, I noticed the tilde/grave key now sends < without a shift modifier and > with a shift modifier. Using fn doesn't seem to change this.

The config I have is:

```
options hid_apple swap_fn_leftctrl=1
options hid_apple swap_opt_cmd=1
```

**Comment by TranquilMarmot** [comment]
Adding the following to the config fixed this:

```
options hid_apple iso_layout=0
```

**Comment by free5lot** [comment]
Yes, that's what I was gonna recommend.
`iso_layout` is a parameter from the original hid_apple and should work the same way.
