### ISSUE TITLE
Support for non apple keyboards?

### ISSUE THREAD

**Issue by bafonso** [free5lot/hid-apple-patched#69]
I have a Logitech K750 keyboard using the unifying logitech wireless-USB receiver with an apple layout as well as other ergonomic apple-layout keyboards (bluetooth). Would it be possible to support other keyboards?

**Comment by free5lot** [comment]
Sorry, hid-apple module is used only for Apple keyboards (external and laptops). I won't work for Logitech or other keyboards.
But you can modify hid modules of other devices by your own.
