### ISSUE TITLE
Option for swapping Cmd and Ctrl

### ISSUE THREAD

**Issue by vitormmatos** [free5lot/hid-apple-patched#90]
Command is used as Ctrl on MacOS, it could be great for those already used to Mac keyboard layouts.

**Comment by gamunu** [comment]
@vitormmatos This option already available. Try setting `swap_ctrl_cmd` to 1 in the options.

**Comment by vitormmatos** [comment]
Thanks @gamunu , I'll check it rn.

**Comment by LeviSnoot** [comment]
@gamunu Can we re-open this issue? I don't see the option you mentioned anywhere in the repo and setting it does nothing.
