### ISSUE TITLE
AUR Package Missing

### ISSUE THREAD

**Issue by sansroot** [free5lot/hid-apple-patched#98]
can't install it from AUR

yay -S hid-apple-patched
 -> No AUR package found for hid-apple-patched
 there is nothing to do

**Comment by sansroot** [comment]
Found a native solution

change parameters from those files and be happy

/sys/bus/hid/drivers/apple/module/parameters

**Comment by sansroot** [comment]
> Found a native solution
> 
> change parameters from those files and be happy
> 
> /sys/bus/hid/drivers/apple/module/parameters

**Comment by tomdevelops** [comment]
Hey @sansroot, just a heads-up that the AUR package has been renamed. The new name is [hid-apple-patched-dkms-git](https://aur.archlinux.org/packages/hid-apple-patched-dkms-git).
